### ISSUE TITLE
SolarApp Organization

### ISSUE THREAD

**Issue by danlopez** [solarapp/solar-api-docs#1]
Hello @mettiuss. I'm the CTO of the SolarApp Foundation (https://solarapp.nrel.gov/), a non-profit in the US working to accelerate the adoption of solar panels. It doesn't appear that your org (`solarapp`) is actively being used; would you be open to changing the name of your organization so that we can use `solarapp`? Thanks so much!

**Comment by mettiuss** [comment]
Hello @danlopez!
Per GitHub’s username policy, exchanging usernames is not permitted, whether free or paid (https://docs.github.com/en/site-policy/other-site-policies/github-username-policy).

The organisation still contains the project and all of its code and it is on GitHub to allow for quick linking and reference.

**Comment by danlopez** [comment]
Hi @mettiuss ! That actually applies to usernames, not organization names - https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization. When you rename an organization, it allows another organization to use the name. That said, not a big deal if it's still in use; I just figured I would ask. Thanks!
